language: node_js

node_js:
  - 8
  - 10
  - 12

branches:
  only:
  - master

jobs:
  include:
    - stage: release
      node_js: 12
      script: npm t && codecov
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release